services:
    # Serviço 1: A Instância do Redis
    - type: redis
      name: bot-redis
      plan: free
      ipAllowList: [] # CORREÇÃO 1: Adicionada lista de permissões de IP (vazia permite acesso interno)

    # Serviço 2: O Serviço Web (Django/Gunicorn)
    - type: web
      name: bot-web
      runtime: python
      plan: free
      buildCommand: "./build.sh"
      startCommand: "gunicorn config.wsgi"
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: bot-database
                property: connectionString
          - key: REDIS_URL
            fromService: # CORREÇÃO 2: 'fromRedis' trocado para 'fromService'
                type: redis # CORREÇÃO 2: Adicionado o tipo de serviço
                name: bot-redis
                property: connectionString
          - key: PYTHON_VERSION
            value: 3.12.6
          - key: SECRET_KEY
            generateValue: true

    # Serviço 3: O Worker em Segundo Plano (Celery)
    - type: worker
      name: bot-worker
      runtime: python
      plan: free
      buildCommand: "pip install -r requirements.txt"
      startCommand: "celery -A config worker -l info -P gevent"
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: bot-database
                property: connectionString
          - key: REDIS_URL
            fromService: # CORREÇÃO 3: 'fromRedis' trocado para 'fromService'
                type: redis # CORREÇÃO 3: Adicionado o tipo de serviço
                name: bot-redis
                property: connectionString
          - key: PYTHON_VERSION
            value: 3.12.6
          - key: SECRET_KEY
            fromService:
                type: web
                name: bot-web
                envVarKey: SECRET_KEY

# Seção separada e correta para o banco de dados
databases:
    # O Banco de Dados PostgreSQL
    - name: bot-database
      plan: free
